#
# Derivation relationships
#
ASK
{
  ?smpTo prov:wasDerivedFrom ?smpFrom. 
  # Every statement like this has also sio:SIO_000244 (derived from)
  ?smpTo sio:SIO_000244 ?smpFrom. 

	?smpFrom sio:SIO_000245 ?smpTo.
	# this is derived into, and prov:hadDerivation is available too
	?smpFrom prov:hadDerivation ?smpTo. 	
}
