# VOID-related graph, you need a $version for this, see test_all.sh
ASK
{ 
  <http://rdf.ebi.ac.uk/dataset/biosamples/$version>
    pav:importedOn ?date;
    pav:version ?ver;
    void:triples ?triples.

  FILTER ( STR ( ?ver ) = "$version" ).
  FILTER ( ?triples > 0 ).    
}
