#
# Samples reporting latitude and longitude
#
ASK
{
  ?item biosd-terms:has-bio-characteristic ?latPv, ?longPv.

  ?latPv
    biosd-terms:has-bio-characteristic-type [ rdfs:label ?latLabel];
    sio:SIO_000300 ?latVal. # sio:has value

  FILTER ( REGEX ( ?latLabel, "latitude", "i" ) ).

  ?longPv
    biosd-terms:has-bio-characteristic-type [ rdfs:label ?longLabel ];
    sio:SIO_000300 ?longVal. # sio:has value

  FILTER ( REGEX ( ?longLabel, "longitude", "i" ) ).
}
